### ISSUE TITLE
ex 3.5 step 1 remove line numbers 

### ISSUE THREAD

**Issue by brikeyes** [docker-training/security-workshop#5]
I would suggest you leave the line numbers out , if the students cut and paste this it is possible to insert indents into the app.py fine unintentionally 

import os
2 print '***** DOCKER Secrets ******'
3 print 'USERNAME: {0}'.format(os.environ['USERNAME'])
4
5 fname = os.environ['PASSWORD_FILE']
6 with open(fname) as f:
7 content = f.readlines()
8
9 print 'PASSWORD_FILE: {0}'.format(fname)
10 print 'PASSWORD: {0}'.format(content[0])

**Comment by katieannemills** [comment]
Thanks, @brikeyes - but this repo is long retired, please direct all comments for Docker training material to https://github.com/docker-training/presentations.
